# Generated by Django 5.2.13 on 2026-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='financial_risk_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_usd_24h', models.CharField(max_length=3000)),
                ('available_supply', models.CharField(max_length=3000)),
                ('idn', models.CharField(max_length=3000)),
                ('last_updated', models.CharField(max_length=3000)),
                ('market_cap_usd', models.CharField(max_length=3000)),
                ('max_supply', models.CharField(max_length=3000)),
                ('name', models.CharField(max_length=3000)),
                ('percent_change_1h', models.CharField(max_length=3000)),
                ('percent_change_24h', models.CharField(max_length=3000)),
                ('percent_change_7d', models.CharField(max_length=3000)),
                ('price_btc', models.CharField(max_length=3000)),
                ('price_usd', models.CharField(max_length=3000)),
                ('rank', models.CharField(max_length=3000)),
                ('symbol', models.CharField(max_length=3000)),
                ('total_supply', models.CharField(max_length=3000)),
                ('Prediction', models.CharField(max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='address',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='gender',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
